### ISSUE TITLE
refrenv.sh did not work for me in Git bash

### ISSUE THREAD

**Issue by mreduar** [badrelmers/RefrEnv#1]
Hi, I tried to run the [refrenv.sh](https://raw.githubusercontent.com/badrelmers/RefrEnv/main/refrenv.sh) from my git bash and it did not update the environment variables for me.
When executing refrenv.sh two of these errors always appear.
![image](https://user-images.githubusercontent.com/22550119/154182957-6e4df6c8-2e44-4558-89de-eb64c75b3693.png)
Perform several tests. It seems that if I add a new variable this variable does appear in the terminal after executing the command, but if I delete the variable and execute the command again, then this variable is still in the console, it is not deleted. For this I have no problem, that does not affect me at all, what happens right now is that I want to update the php PATH to a new version, but the console keeps telling me to have a different version.

Watch [this](https://youtu.be/hEYLydC-ElM) video, maybe it explains a little more.

**Comment by mreduar** [comment]
Hi! 
I have run the new RefrEnv and now it works! It's great

However when I run it I get some errors. Here is the content of the `log.txt`
```
which: no bash in ((null))
/c/Users/Eduar/.bash_profile: line 5: oh-my-posh: command not found
cygpath: can't convert empty path
cygpath: can't convert empty path
```

This is the content of my `.bash_profile`
```
# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

eval "$(oh-my-posh --init --shell bash --config ~/craver.omp.json)"
```
It seems that the `oh-my-posh` path is lost in the process.

**Comment by badrelmers** [comment]
I found the problem, after I installed Chocolatey I got the same error: `cygpath: can't convert empty path`

download the last RefrEnv I solve it.

if you are interested in understanding why this happened read this:
after installing Chocolatey it adds itself to the path like that: `C:\ProgramData\chocolatey\bin;` , the last `;` should not have been added by Chocolatey, this is an error by Chocolatey not RefrEnv. if you look at your PATH you will see double `;;` or if Chocolatey was the last thing you installed then you will see some thing like that: (see the last `;`)
![image](https://user-images.githubusercontent.com/40046489/154596407-c286c9c6-f463-4a1e-9160-b734dedda10c.png)

this is why cygpath says "can't convert empty path" , `;;` is an empty path.

Note: this can happen by any other program that adds a `;` in the end. so if you did not install Chocolatey then for sure you installed something that do the same thing I described above.

RefrEnv will work fine now when this happen.

**Comment by mreduar** [comment]
I assumed it would be something related to that, an empty path.
The other two errors still came up.
![image](https://user-images.githubusercontent.com/22550119/154599243-2939e2ff-9df3-4ad8-bd92-1c4cdd24ee5f.png)
But I can avoid them if I do something like this
![image](https://user-images.githubusercontent.com/22550119/154599469-06a5e8bc-a413-44a6-8018-9d74da36fb63.png)

For now refreshing the path is enough for me, thanks for your help!

**Comment by badrelmers** [comment]
I could not reproduce those two errors.
please add `set -x` at the beginning of RefrEnv.sh, then run this again:
`(RefrEnv_ResetPath=yes ; source refrenv.sh) >log.txt 2>log.txt`
then upload the log.txt

I do not advice you to hide the error, it should be solved.

**Comment by mreduar** [comment]
[Here](https://ghostbin.com/Zcs0f) is the log.

**Comment by badrelmers** [comment]
please download the new RefrEnv, I solved those errors, and added a better way to reset the PATH.

**Comment by mreduar** [comment]
Great, now it works like a charm! Thank you very much!
Is it possible that when I open a new tab, i.e. another Git Bash console, the variables are updated there as well? Or is it not possible to do this without running the command?

**Comment by badrelmers** [comment]
but generally you can automate this using .bashrc or .bash_profile ..etc

**Comment by mreduar** [comment]
Ok, thank you very much for your help
