### ISSUE TITLE
Running into errors when trying the source refrenv.sh command in git bash with ZSH installed

### ISSUE THREAD

**Issue by hdecoded** [badrelmers/RefrEnv#2]
Hi,

I Installed ZSH on top of git bash in windows and am trying to run source refrenv.sh but running in to the following issues 

```
➜  RefrEnv git:(main) ✗ source refrenv.sh
RefrEnv - Refresh the Environment for Bash
i=$'asl.log\nDriverData\nJAVA_HOME\nM2_HOME\nMAVEN_HOME\nPSModulePath\nSNC_LIB\nSNC_LIB_64\nSSF_LIBRARY_PATH\nSSF_LIBRARY_PATH_64\nUATDATA\nZES_ENABLE_SYSMAN'
Error (2): The system cannot find the file specified.

getNewlyAddedVars:local:69: not valid in this context: ALLnewVarsKeysAndValues+
refrenv.sh:source:365: no such file or directory: /tmp/RefrEnvBash_20230530_140437_932623844/newEnv.sh
```

Could you please let me know If I need to make any changes to the script for it to work in zsh or any of my configuration is causing this issue.

**Comment by hdecoded** [comment]
reverted back to bash and tried the same hoping it would work in the bash but got the following error 

```
$ source refrenv.sh
RefrEnv - Refresh the Environment for Bash
bash: export: `asl.log=Destination=file': not a valid identifier
```

**Comment by badrelmers** [comment]
zsh was not supported, I added support for it now, you have to use this one for zsh https://github.com/badrelmers/RefrEnv/blob/main/refrenvz.sh

but I m not a zsh expert, for now it works fine, but i cannot be sure that everything is ok as in bash.
![image](https://github.com/badrelmers/RefrEnv/assets/40046489/02d9eca1-7025-4f4a-aa4e-98e0d751be39)
_________________________________________________________
I could not reproduce the error you get in bash, in my git bash works fine
![image](https://github.com/badrelmers/RefrEnv/assets/40046489/f10160b7-1928-47e7-95f6-a161db861cbd)

please run it like that to debug it
```bash
RefrEnv_debug=yes
source refrenv.sh
```

a new window will be opened containing multiple files, open the file called newEnv.sh and copy past its content here, or better compress all the folder and upload it somewhere and send me the link.

**Comment by hdecoded** [comment]
I ran the following code and it opened a folder but the folder is empty

```
RefrEnv_debug=yes
source refrenv.sh

```
This is the output after enabling debug

```
➜  Workspaces source refrenv.sh
RefrEnv - Refresh the Environment for Bash - (Debug enabled)
i=$'asl.log\nDriverData\nJAVA_HOME\nM2_HOME\nMAVEN_HOME\nPSModulePath\nSNC_LIB\nSNC_LIB_64\nSSF_LIBRARY_PATH\nSSF_LIBRARY_PATH_64\nUATDATA\nZES_ENABLE_SYSMAN'
Error (2): The system cannot find the file specified.

getNewlyAddedVars:local:69: not valid in this context: ALLnewVarsKeysAndValues+
/c/Workspaces/Env_Variables/RefrEnv/refrenv.sh:source:365: no such file or directory: /tmp/RefrEnvBash_20230601_104034_782419576/newEnv.sh
```

**Comment by badrelmers** [comment]
- what version of git bash you have installed? do you install it using the default setup? 
- whats your OS
- does the zsh version of refrenv works fine?

it seems to me that zsh is who run refrenv.sh when you source it from bash
please run this from bash and copy past all the output
```bash
set
set -x
source refrenv.sh`
```

**Comment by hdecoded** [comment]
Thanks for adding the support for zsh @badrelmers. The issue is fixed now.
