### ISSUE TITLE
RefrEnv_ResetPath=yes failing using ZSH on Git Bash

### ISSUE THREAD

**Issue by hdecoded** [badrelmers/RefrEnv#3]
When I set `RefrEnv_ResetPath=yes` and run `source refrenvz.sh` I am getting the following error in zsh 

```
RefrEnv - Refresh the Environment for Zsh - (Reset Path)
getNewPATHS:47: command not found: shopt
env: '': No such file or directory
/c/Workspaces/Env_Variables/RefrEnv/refrenvz.sh:390: command not found: rm
```

I think this also effects the default 'source refrenvz.sh' since the edited environment variable is getting updated but path is not getting updated after running `source refrenvz.sh`

Please let me know if you need more information.

**Comment by badrelmers** [comment]
I uploaded a new refrenv version which solves this bug and other bugs. now refrenv version for zsh is 1.0, so you can use it safely.

**Comment by hdecoded** [comment]
I just downloaded the latest version. the issue is fixed. But I am running to into another issue.

I am updating the JAVA_HOME variable in the environment variables. and running the source refrenvz.sh to change the java version without restarting git bash.

JAVA_HOME variable gets updated in git bash and path_expanded.txt has the correct path but when I echo $PATH in git bash. The old JAVA_HOME path is at the top of the path and new JAVA_HOME path is at the bottom. 

Since the java uses the top most path its still using the old JAVA_HOME path

Is there a possible way to append the new path to the start or fix the code so that the old path does not show up at all ?

**Comment by badrelmers** [comment]
refrenv should not manipulate the path in any way, it should do exactly what windows does when you open a new console. now, when you open a new console you will have the same problem, so refrenv is doing the right thing. the problem come from the way you install java. you have to make a script to install java and change the path as needed after the install from this script, I only know one tool that is able to prepend to the path, `setenv` https://www.codeproject.com/Articles/12153/SetEnv , or its fork `regenv` https://github.com/xparq/regenv/blob/master/README.txt :

## setenv
works on 9x/NT/2000/XP/S2K3/Vista/7/8/10/11
run this from a script
```batch
:: prepend to System PATH
setenv.exe -ap path %%"%var%"

:: append to System PATH
setenv.exe -a path %%"%var%"
```
from the console you have to use one `%`: `setenv.exe -ap path %"%var%"`
## regenv
```batch
:: Note about PATH: if you edit the path it is better to use -x because it converts the reg type from REG_SZ to REG_EXPAND_SZ, this is what windows  does by default too.
:: prepend to System PATH
regenv.exe set -nS -sp -x PATH "%var%"
:: append to System PATH
regenv.exe set -nS -sa -x PATH "%var%"
```
